spring:
  application:
    name: spring-boot-rsocket-consumer-rpc
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
rsocket:
  producer:
    host: localhost
    port: 7000
